#!/bin/bash

OUTPUT_FILE="Raport1_$(date +%d.%m.%Y-%H:%M)_$(hostname).md"
USERNAME="kali"
echo "$DATE"
echo -e "\t\t\tRAPORT\nWojciech Malinowski 279496 &  Karol Gebski 279408\n------------------------------------------------------------------------------\n" > "$OUTPUT_FILE"
echo -e "kali user processes: ps -u kali -f\n" >> "$OUTPUT_FILE"
ps -u $USERNAME -f | head -n 11 >> "$OUTPUT_FILE"
echo -e "\ntop 10 processes CPU desc: ps -eo user,pid,%cpu,%mem,start,time,cmd --sort=-%cpu\n" >> "$OUTPUT_FILE"
ps -eo user,pid,%cpu,%mem,start,time,cmd --sort=-%cpu | head -n 11 >> "$OUTPUT_FILE"
echo -e "\ntop 10 processes MEM desc: ps -eo user,pid,%cpu,%mem,start,time,cmd --sort=-%mem \n" >> "$OUTPUT_FILE"
ps -eo user,pid,%cpu,%mem,start,time,cmd --sort=-%mem | head -n 11 >> "$OUTPUT_FILE"
echo -e "\nlist of processes with effective root user (-u flag): ps aux -u root | head -n 11\n" >> "$OUTPUT_FILE"
ps aux -u root | head -n 11 >> "$OUTPUT_FILE"
echo -e "\nprocess list in tree form, if PPID of process equals 1 it was started by systemd PID=1 (last 3 here): ps -eo pid,ppid,user,cmd --forest\n" >> "$OUTPUT_FILE"
ps -eo pid,ppid,user,cmd --forest | head -n 10 >> "$OUTPUT_FILE"
ps -eo pid,ppid,user,cmd | awk '$2==1' | head -n 3 >> "$OUTPUT_FILE"
echo -e "\n list installed applications:\n dpkg -l | head -n 15\n" >> "$OUTPUT_FILE"
dpkg -l | head -n 15 >> "$OUTPUT_FILE"
echo -e "\nopenssh-server version $(dpkg -l | grep openssh-server | awk '{print $3}')\n" >> "$OUTPUT_FILE"
echo -e "\nVery Safe File Transfer Protocol Daemon has been installed $(cat /var/log/dpkg.log* | grep ' installed vsftpd' | awk '{print $1}') at $(cat /var/log/dpkg.log | grep ' installed vsftpd' | awk '{print $2}')\n" >> "$OUTPUT_FILE"
echo -e "\n10 dpkg programs successfully installed last week (grep ' installed' /var/log/dpkg.log | awk -v  date="$(date -d '7 days ago' '+%Y-%m-%d')" '$1 >= date {print $5}' | cut --delimiter ":" --fields 1 | head -n 10):\n" >> "$OUTPUT_FILE"
grep " installed" /var/log/dpkg.log | awk -v  date="$(date -d '7 days ago' '+%Y-%m-%d')" '$1 >= date {print $5}' | cut --delimiter ":" --fields 1 | head -n 10 >> "$OUTPUT_FILE"
echo -e "\nlist of listening ports ss -tuln | awk '{print $5}| rev | cut -s --delimiter ':' --fields 1 | rev | sort -u':\n" >> "$OUTPUT_FILE"
ss -tuln | awk '{print $5}' | rev | cut -s --delimiter ':' --fields 1 | rev | sort -u >> "$OUTPUT_FILE"
echo -e "\nservices to be found listening on 0.0.0.0 (ss -tuln | grep -E '0.0.0.0:|\*:')\n" >> "$OUTPUT_FILE"
ss -tuln | grep -E '0.0.0.0:|\*:' >> "$OUTPUT_FILE"
echo -e "\nprocesses (users) responsible for port 22 state sudo ss -tulpn | grep :22\n" >> "$OUTPUT_FILE"
sudo ss -tulpn | grep :22  >> "$OUTPUT_FILE"
echo -e "\nself scan for ssh version port 22 (nmap -sV -p22 0.0.0.0 | grep 22) and wikipedia for 80 (nmap -sV -p80 185.15.59.224  | grep 80)\n" >> "$OUTPUT_FILE"
nmap -sV -p22 0.0.0.0 | grep 22 >> "$OUTPUT_FILE"
nmap -sV -p80 185.15.59.224  | grep 80 >> "$OUTPUT_FILE"
echo -e "\nchecking status of ssh and apache2 services (sudo systemctl status ssh/apache2)\n" >> "$OUTPUT_FILE"
sudo systemctl status ssh >> "$OUTPUT_FILE"
sudo systemctl status apache2 >> "$OUTPUT_FILE"
echo -e "\nlist 10 out of all active services ( systemctl list-units --state active | head -n 11)\n" >> "$OUTPUT_FILE"
systemctl list-units --state active | head -n 11 >> "$OUTPUT_FILE"
echo -e "\nlist of 10 services that activate on system start (enabled) sudo systemctl list-unit-files | awk '{print $1,$2}' | grep enabled | awk '{print $1}' | head -n 10\n" >> "$OUTPUT_FILE" 
sudo systemctl list-unit-files | awk '{print $1,$2}' | grep enabled | awk '{print $1}' | head -n 10 >> "$OUTPUT_FILE"
echo -e "\nlist all users of system awk -F':' '$2 ~ "$" {print $1}' /etc/passwd | head -n 10\n" >> "$OUTPUT_FILE"
awk -F':' '$2 ~ "$" {print $1}' /etc/passwd | head -n 10  >> "$OUTPUT_FILE"
echo -e "\nusers with shell access: awk -F: '$7 ~ /(bash|sh|zsh)$/ {print $1}' /etc/passwd\n" >> "$OUTPUT_FILE"
awk -F: '$7 ~ /(bash|sh|zsh)$/ {print $1}' /etc/passwd >> "$OUTPUT_FILE"
echo -e "\n better way to check similar things, in this case users that can use sudo, is with getent: getent group sudo\n" >> "$OUTPUT_FILE"
getent group sudo >> "$OUTPUT_FILE"
echo -e "\ncrontab of root user: sudo crontab -l" >> "$OUTPUT_FILE"
sudo crontab -l >> "$OUTPUT_FILE"
echo -e "\nftp logs: sudo cat /var/log/vsftpd.log | head -n 10" >> "$OUTPUT_FILE"
sudo cat /var/log/vsftpd.log | head -n 10 >> "$OUTPUT_FILE"
echo -e "\nssh logs sudo journalctl --unit ssh | head -n 15\n">> "$OUTPUT_FILE"
sudo journalctl --unit ssh | head -n 15 >> "$OUTPUT_FILE"
echo -e "\napparmor status sudo apparmor_status\n" >> "$OUTPUT_FILE"
sudo apparmor_status | head -n 16 >> "$OUTPUT_FILE"
